sudo: false
language: node_js
node_js:
  - "4.2.2"
  - "0.12"
script:
  - npm install -g bower karma
  - $CI_ACTION
env:
  matrix:
  - CI_ACTION="gulp test"
  - CI_ACTION="gulp lint"
  - CI_ACTION="gulp static"
  - CI_ACTION="gulp cordova"
