language: node_js
node_js:
  - "0.12"
  - "iojs"
  - "0.10"
script:
  - npm install -g grunt-cli bower karma
  - $CI_ACTION
env:
  matrix:
  - CI_ACTION="grunt"
  - CI_ACTION="grunt test"
  - CI_ACTION="grunt static"
  - CI_ACTION="grunt dynamic"
  - CI_ACTION="grunt cordova"
  - CI_ACTION="grunt pack"
  - CI_ACTION="grunt karma"
  - CI_ACTION="grunt mochacov:travis"
